Repository TeamAvAb/AvAb-Back, pull requests merged in 2024-01, with the labels that each got.

#2 Ci: 환경 설정
  .ebextensions-dev/00-makerFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
Labels: ci

#4 👷 [CI]: Ci/CD 파이프라인 구축
  .ebextensions-dev/00-makerFiles.config
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/com/avab/avab/AvAbApplication.java
  src/main/java/com/avab/avab/controller/RootController.java
  src/main/resources/application.yml
  src/test/java/com/avab/avab/AvAbApplicationTests.java
Labels: 👷 ci

#7 :sparkles: [Feat]: Swagger UI 라이브러리 추가 및 설정
  build.gradle
  src/main/java/com/avab/avab/config/SwaggerConfig.java
  src/main/java/com/avab/avab/controller/RootController.java
  src/main/resources/application.yml
Labels: :memo: docs, :sparkles: feature

#8 :sparkles: API 응답통일/ 에러 핸들러
  src/main/java/com/avab/avab/apiPayload/ApiResponse.java
  src/main/java/com/avab/avab/apiPayload/code/BaseCode.java
  src/main/java/com/avab/avab/apiPayload/code/BaseErrorCode.java
  src/main/java/com/avab/avab/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/avab/avab/apiPayload/code/ReasonDTO.java
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/avab/avab/apiPayload/exception/GeneralException.java
Labels: :sparkles: feature

#10 🔧 [S3] S3: 환경 설정
  build.gradle
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/S3/S3Exception.java
  src/main/java/com/avab/avab/aws/s3/AmazonS3Manager.java
  src/main/java/com/avab/avab/config/AmazonConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: feature

#12 ✨ [Feat]: Entity 생성
  src/main/java/com/avab/avab/config/EnableJpaAuditingConfig.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/domain/RecreationAge.java
  src/main/java/com/avab/avab/domain/RecreationGender.java
  src/main/java/com/avab/avab/domain/RecreationHashtag.java
  src/main/java/com/avab/avab/domain/RecreationKeyword.java
  src/main/java/com/avab/avab/domain/RecreationPlace.java
  src/main/java/com/avab/avab/domain/RecreationPreparation.java
  src/main/java/com/avab/avab/domain/RecreationReview.java
  src/main/java/com/avab/avab/domain/RecreationWay.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/domain/common/BaseEntity.java
  src/main/java/com/avab/avab/domain/enums/Age.java
  src/main/java/com/avab/avab/domain/enums/Gender.java
  src/main/java/com/avab/avab/domain/enums/Keyword.java
  src/main/java/com/avab/avab/domain/enums/Place.java
  src/main/java/com/avab/avab/domain/enums/RecommendationType.java
  src/main/java/com/avab/avab/domain/enums/SocialType.java
  src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
  src/main/java/com/avab/avab/domain/mapping/RecreationRecreationKeyword.java
  src/main/java/com/avab/avab/domain/mapping/RecreationReviewRecommendation.java
Labels: :sparkles: feature

#14 Feat: 시큐리티 설정
  build.gradle
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/auth/AuthException.java
  src/main/java/com/avab/avab/auth/filter/JwtRequestFilter.java
  src/main/java/com/avab/avab/auth/jwt/JwtTokenProvider.java
  src/main/java/com/avab/avab/auth/principal/PrincipalDetails.java
  src/main/java/com/avab/avab/auth/principal/PrincipalDetailsService.java
  src/main/java/com/avab/avab/auth/test/AuthController.java
  src/main/java/com/avab/avab/auth/test/AuthService.java
  src/main/java/com/avab/avab/auth/test/dto/LoginRequest.java
  src/main/java/com/avab/avab/auth/test/dto/LoginResponse.java
  src/main/java/com/avab/avab/config/SecurityConfig.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/domain/RecreationAge.java
  src/main/java/com/avab/avab/domain/RecreationGender.java
  src/main/java/com/avab/avab/domain/RecreationHashtag.java
  src/main/java/com/avab/avab/domain/RecreationKeyword.java
  src/main/java/com/avab/avab/domain/RecreationReview.java
  src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
  src/main/java/com/avab/avab/repository/UserRepository.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#17 :bug: Fix: 시큐리티 수정
  src/main/java/com/avab/avab/config/SecurityConfig.java
Labels: :bug: bug

#22 ✨ [FEAT]: 인기 레크레이션 목록 조회 API
  src/main/java/com/avab/avab/apiPayload/BaseResponse.java
  src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/avab/avab/auth/test/AuthController.java
  src/main/java/com/avab/avab/config/SecurityConfig.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/dto/recreation/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature

#24 ✨ [Feat]: 사용자 추출 어노테이션 구현, CORS 설정, Swagger 설정 수정
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/AuthException.java
  src/main/java/com/avab/avab/apiPayload/exception/S3Exception.java
  src/main/java/com/avab/avab/apiPayload/exception/UserException.java
  src/main/java/com/avab/avab/aws/s3/AmazonS3Manager.java
  src/main/java/com/avab/avab/config/SecurityConfig.java
  src/main/java/com/avab/avab/config/SwaggerConfig.java
  src/main/java/com/avab/avab/config/WebConfig.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/security/filter/JwtRequestFilter.java
  src/main/java/com/avab/avab/security/handler/annotation/AuthUser.java
  src/main/java/com/avab/avab/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/com/avab/avab/security/principal/PrincipalDetails.java
  src/main/java/com/avab/avab/security/principal/PrincipalDetailsService.java
  src/main/java/com/avab/avab/security/provider/JwtTokenProvider.java
  src/main/java/com/avab/avab/security/test/AuthController.java
  src/main/java/com/avab/avab/security/test/AuthService.java
  src/main/java/com/avab/avab/security/test/dto/LoginRequest.java
  src/main/java/com/avab/avab/security/test/dto/LoginResponse.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#29 ✨ [Feat]: 레크레이션 검색 API 구현
  build.gradle
  src/main/generated/com/avab/avab/domain/QRecreation.java
  src/main/generated/com/avab/avab/domain/QRecreationAge.java
  src/main/generated/com/avab/avab/domain/QRecreationGender.java
  src/main/generated/com/avab/avab/domain/QRecreationHashtag.java
  src/main/generated/com/avab/avab/domain/QRecreationKeyword.java
  src/main/generated/com/avab/avab/domain/QRecreationPlace.java
  src/main/generated/com/avab/avab/domain/QRecreationPreparation.java
  src/main/generated/com/avab/avab/domain/QRecreationReview.java
  src/main/generated/com/avab/avab/domain/QRecreationWay.java
  src/main/generated/com/avab/avab/domain/QUser.java
  src/main/generated/com/avab/avab/domain/common/QBaseEntity.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationFavorite.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationRecreationKeyword.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationReviewRecommendation.java
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/avab/avab/apiPayload/exception/RecreationException.java
  src/main/java/com/avab/avab/config/QueryDslConfig.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/domain/enums/Age.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
  src/main/java/com/avab/avab/validation/annotation/ValidatePage.java
  src/main/java/com/avab/avab/validation/validator/PageValidator.java
Labels: :sparkles: feature, :recycle: refactor

#34 :construction_worker: [CI]: 코드 포맷팅을 위한 pre-commit Git Hooks 추가
  .script/pre-commit
  build.gradle
  src/main/java/com/avab/avab/controller/RecreationController.java
Labels: 👷 ci

#39 :sparkles: [Feat]: 레크레이션 리뷰 작성 API 구현
  src/main/java/com/avab/avab/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/RecreationReview.java
  src/main/java/com/avab/avab/dto/reqeust/RecreationRequestDTO.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationReviewRepository.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature

#44 ✨ [FEAT] 즐겨 찾는 레크레이션 조회 API
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/repository/RecreationFavoriteRepository.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#45 ✨ [Feat]: 레크레이션 리뷰 추천 토글 API 구현
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/RecreationReviewException.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/controller/RecreationReviewController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/converter/RecreationReviewConverter.java
  src/main/java/com/avab/avab/domain/mapping/RecreationReviewRecommendation.java
  src/main/java/com/avab/avab/dto/reqeust/RecreationReviewRequestDTO.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/dto/response/RecreationReviewResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationReviewRecommendationRepository.java
  src/main/java/com/avab/avab/repository/RecreationReviewRepository.java
  src/main/java/com/avab/avab/service/RecreationReviewService.java
  src/main/java/com/avab/avab/service/impl/RecreationReviewServiceImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
  src/main/java/com/avab/avab/validation/annotation/ExistRecreationReview.java
  src/main/java/com/avab/avab/validation/validator/ExistRecreationReviewValidator.java
Labels: :sparkles: feature, :recycle: refactor

#52 :sparkles: [Feat]: 주간 조회수 업데이트 배치 추가
  src/main/java/com/avab/avab/batch/UpdateRecreationViewCountConfig.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
Labels: :sparkles: feature

#31 :sparkles: [Feat]: 카카오 로그인 구현
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/config/WebConfig.java
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/converter/AuthConverter.java
  src/main/java/com/avab/avab/dto/KakaoProfile.java
  src/main/java/com/avab/avab/dto/OAuthToken.java
  src/main/java/com/avab/avab/dto/response/AuthResponseDTO.java
  src/main/java/com/avab/avab/redis/domain/RefreshToken.java
  src/main/java/com/avab/avab/redis/repository/RefreshTokenRepository.java
  src/main/java/com/avab/avab/redis/service/RefreshTokenService.java
  src/main/java/com/avab/avab/repository/UserRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/security/handler/annotation/ExtractToken.java
  src/main/java/com/avab/avab/security/handler/resolver/ExtractTokenArgumentResolver.java
  src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
  src/main/java/com/avab/avab/security/test/TestAuthController.java
  src/main/java/com/avab/avab/security/test/TestAuthService.java
  src/main/java/com/avab/avab/security/test/dto/LoginResponse.java
  src/main/java/com/avab/avab/service/AuthService.java
  src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#49 :sparkles: [Feat]: 회원 정보 수정 API 구현
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/UserConverter.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/dto/reqeust/UserRequestDTO.java
  src/main/java/com/avab/avab/dto/response/UserResponseDTO.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#55 ✨ [Feat]: 레크레이션 검색 요구사항에 맞추어 수정
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/enums/Keyword.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :memo: docs, :sparkles: feature

#57 :sparkles: [Feat]: 플로우 즐겨 찾기 추가
  src/main/generated/com/avab/avab/domain/QFlow.java
  src/main/generated/com/avab/avab/domain/QUser.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowFavorite.java
  src/main/java/com/avab/avab/domain/Flow.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/domain/mapping/FlowFavorite.java
Labels: :sparkles: feature

#53 ✨ [Feat] 연관 레크레이션 목록 API구현 및 예외처리 추가
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#62 ✨ [Feat]: 플로우 목록 조회 API 구현
  src/main/generated/com/avab/avab/domain/QFlow.java
  src/main/generated/com/avab/avab/domain/QFlowAge.java
  src/main/generated/com/avab/avab/domain/QFlowGender.java
  src/main/generated/com/avab/avab/domain/QUser.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowFavorite.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowRecreation.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowRecreationKeyword.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowRecreationPurpose.java
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/domain/Flow.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/domain/mapping/FlowFavorite.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#64 ✨ [Feat]: 내가 만든 플로우 조회 API
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/security/test/TestAuthController.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#65 ✨ [Feat]: 플로우 상세 설명 조회 API
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#67 :sparkles: [Feat] 스크랩 플로우 API 구현
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/UserConverter.java
  src/main/java/com/avab/avab/domain/RecreationPurpose.java
  src/main/java/com/avab/avab/repository/FlowFavoriteRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#70 :sparkles: [Feat]: 레크레이션 프리뷰 응답에 summary 추가
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
Labels: :sparkles: feature
