Repository TeamAvAb/AvAb-Back, pull requests merged in 2024-09, with the labels that each got.

#162 ✨ [Feat] 삭제, 신고된 게시글 마스킹 처리 - 레크레이션 인기/추천, 플로우 추천
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/repository/FlowCustomRepository.java
  src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/MaskingPredicates.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#165 🐛 [Fix]: 레크레이션 필터링 버그 해결
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :bug: bug

#168 🐛 [Fix]: 활동정지 사용자 필터 수정 구현
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/security/filter/DisabledUserFilter.java
  src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
Labels: :sparkles: feature

#170 ✨ [Feat]: 소셜 로그인 로컬 테스트용 API 추가
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/converter/AuthConverter.java
  src/main/java/com/avab/avab/dto/KakaoProfile.java
  src/main/java/com/avab/avab/dto/OAuthToken.java
  src/main/java/com/avab/avab/feign/kakao/KaKaoOAuthFeignConfig.java
  src/main/java/com/avab/avab/feign/kakao/dto/response/KakaoOAuthResponseDTO.java
  src/main/java/com/avab/avab/feign/kakao/service/KakaoApiClient.java
  src/main/java/com/avab/avab/feign/kakao/service/KakaoOAuthClient.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
  src/main/java/com/avab/avab/service/AuthService.java
  src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature

#172 :bug: [Fix]: 인기 레크레이션 미로그인시 조회 안되는 문제 수정
  src/main/java/com/avab/avab/repository/MaskingPredicates.java
Labels: :bug: bug

#176 ✨ [Feat]: 보안 관련 기능 적용
  src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/security/filter/DisabledUserFilter.java
  src/main/java/com/avab/avab/security/filter/JwtRequestFilter.java
  src/main/java/com/avab/avab/security/handler/SwaggerLoginSuccessHandler.java
  src/main/java/com/avab/avab/security/handler/resolver/ExtractTokenArgumentResolver.java
  src/main/java/com/avab/avab/security/principal/PrincipalDetailsService.java
  src/main/java/com/avab/avab/security/provider/KakaoAuthProvider.java
  src/main/java/com/avab/avab/security/test/TestAuthController.java
  src/main/java/com/avab/avab/security/test/TestAuthService.java
  src/main/java/com/avab/avab/service/AuthService.java
  src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
  src/main/java/com/avab/avab/utils/EnvironmentHelper.java
  src/main/resources/application.yml
Labels: :bug: bug, :sparkles: feature, :recycle: refactor
