Repository TeamAvAb/AvAb-Back, pull requests merged in 2024-10, with the labels that each got.

#179 🐛 [Fix]: searchRecreations 코드 수정
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
Labels: :bug: bug

#181 :bug: [Fix]: 리뷰 추천/비추천시 카운트 수정
  src/main/java/com/avab/avab/domain/RecreationReview.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/security/test/dto/LoginRequest.java
  src/main/java/com/avab/avab/service/impl/RecreationReviewServiceImpl.java
Labels: :bug: bug

#187 ✨ [Feat]: 프로메테우스 액츄에이터 추가 및 설정
  build.gradle
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#186 ✨ [Feat]: 레크레이션 API 통합
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/domain/Report.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/dto/enums/MaskedReason.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/repository/MaskingPredicates.java
  src/main/java/com/avab/avab/repository/QueryDslUtil.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
  src/main/java/com/avab/avab/repository/RecreationReviewRepository.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
  src/main/java/com/avab/avab/service/impl/ReportServiceImpl.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :recycle: refactor

#183 :sparkles: [Feat]: 마스킹 관련 고도화
  src/main/java/com/avab/avab/controller/ReportController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/converter/UserConverter.java
  src/main/java/com/avab/avab/domain/Flow.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/domain/mapping/FlowScrap.java
  src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
  src/main/java/com/avab/avab/domain/mapping/RecreationReviewRecommendation.java
  src/main/java/com/avab/avab/repository/FlowCustomRepository.java
  src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/FlowFavoriteRepository.java
  src/main/java/com/avab/avab/repository/FlowScrapRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/RecreationFavoriteRepository.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/ReportServiceImpl.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :bug: bug, :sparkles: feature

#189 ♻️ [Refactor]: refresh token Bearer 토큰 추가
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/security/handler/resolver/ExtractTokenArgumentResolver.java
Labels: :memo: docs, :recycle: refactor
