Repository TeamAvAb/AvAb-Back, pull requests merged in 2024-02, with the labels that each got.

#73 ✨ [Feat]: 레크레이션 게시 API 구현
  src/main/generated/com/avab/avab/domain/QRecreationWay.java
  src/main/java/com/avab/avab/aws/s3/AmazonS3Manager.java
  src/main/java/com/avab/avab/aws/s3/S3Directory.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/domain/Recreation.java
  src/main/java/com/avab/avab/domain/RecreationWay.java
  src/main/java/com/avab/avab/dto/reqeust/RecreationRequestDTO.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/repository/RecreationKeywordRepository.java
  src/main/java/com/avab/avab/repository/RecreationPurposeRepository.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
  src/main/java/com/avab/avab/utils/MultipartJackson2HttpMessageConverter.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#82 :ambulance: [HOTFIX]: 레디스 연결 문제 해결
  src/main/java/com/avab/avab/config/RedisConfig.java
Labels: :bug: bug

#76 :sparkles: [Feat]: 레크레이션 추천 기능
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#86 :sparkles: [Feat] 최신 레크레이션 목록 API 구현
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/RecreationRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/RecreationService.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature

#78 ✨ [Feat]: 플로우 조회수 업데이트 스케쥴러 구현
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/FlowException.java
  src/main/java/com/avab/avab/batch/FlowViewCountItemReader.java
  src/main/java/com/avab/avab/batch/SchedulerConfig.java
  src/main/java/com/avab/avab/batch/UpdateRecreationViewCountConfig.java
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/redis/repository/FlowViewCountRepository.java
  src/main/java/com/avab/avab/redis/repository/FlowViewCountRepositoryImpl.java
  src/main/java/com/avab/avab/redis/service/FlowViewCountService.java
  src/main/java/com/avab/avab/redis/service/impl/FlowViewCountServiceImpl.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/validation/annotation/ExistFlow.java
  src/main/java/com/avab/avab/validation/validator/ExistFlowValidator.java
Labels: :sparkles: feature

#83 :memo: [Docs]: 엔드포인트 및 문서 수정
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/controller/RecreationReviewController.java
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
Labels: :recycle: refactor

#90 :bug: [Fix]: Gender 추가 및 null check 추가
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/reqeust/RecreationRequestDTO.java
Labels: :bug: bug

#87 ✨ [Feat]: 플로우 스크랩 API 구현
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/repository/FlowFavoriteRepository.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#93 :bug: [Fix]: BaseEntity 상속
  src/main/generated/com/avab/avab/domain/mapping/QFlowFavorite.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationFavorite.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationReviewRecommendation.java
  src/main/java/com/avab/avab/domain/mapping/FlowFavorite.java
  src/main/java/com/avab/avab/domain/mapping/RecreationFavorite.java
  src/main/java/com/avab/avab/domain/mapping/RecreationReviewRecommendation.java
Labels: :bug: bug

#94 ✨ [Feat] 레크레이션 상세페이지 추가 및 최신레크레이션 api 수정
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
Labels: :sparkles: feature, :recycle: refactor

#98 📝 [Docs]: 로그인 swagger 수정
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/controller/RecreationController.java
Labels: :memo: docs, :recycle: refactor

#96 :bug: [Fix]: 레크레이션 리뷰 게시할 때 별점 업데이트 되도록 수정
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepository.java
  src/main/java/com/avab/avab/repository/RecreationCustomRepositoryImpl.java
  src/main/java/com/avab/avab/service/impl/RecreationServiceImpl.java
Labels: :sparkles: feature

#100 ✨ [Feat] 레크레이션 상세페이지 불러올 내역 추가
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
Labels: :sparkles: feature, :recycle: refactor

#102 :recycle: [Refactor]: 요구사항에 맞추어 enum 수정
  src/main/java/com/avab/avab/domain/enums/Age.java
  src/main/java/com/avab/avab/domain/enums/Keyword.java
  src/main/java/com/avab/avab/domain/enums/Purpose.java
Labels: :recycle: refactor

#91 ✨ [Feat]: 플로우 삭제 API 구현
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#104 ✨ [Feat]: 회원가입시 닉네임 랜덤 생성
  src/main/java/com/avab/avab/controller/AuthController.java
  src/main/java/com/avab/avab/converter/AuthConverter.java
  src/main/java/com/avab/avab/service/impl/AuthServiceImpl.java
  src/main/java/com/avab/avab/utils/RandomUsername.java
Labels: :sparkles: feature

#106 ✨ [Feat]: 플로우 관련 엔티티 수정
  src/main/generated/com/avab/avab/domain/QCustomRecreation.java
  src/main/generated/com/avab/avab/domain/mapping/QFlowRecreation.java
  src/main/generated/com/avab/avab/domain/mapping/QRecreationRecreationKeyword.java
  src/main/java/com/avab/avab/domain/CustomRecreation.java
  src/main/java/com/avab/avab/domain/mapping/FlowRecreation.java
  src/main/java/com/avab/avab/domain/mapping/RecreationRecreationKeyword.java
Labels: :sparkles: feature

#109 :bug: [Fix]: 플로우 목록 조회 인증 요구하는 문제 해결
  src/main/java/com/avab/avab/security/SecurityConfig.java
Labels: :bug: bug

#111 :sparkles: [Feat]: AuthException 처리하는 예외 핸들링 필터 추가
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/security/filter/AuthExceptionHandlingFilter.java
Labels: :sparkles: feature

#113 ✨ [Feat] 플로우 생성시 추천 플로우 API 구현
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/repository/FlowCustomRepository.java
  src/main/java/com/avab/avab/repository/FlowCustomRepositoryImpl.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#114 ♻️ [Refactor]: 플로우 생성에 사용자 지정 레크레이션 추가
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/dto/reqeust/FlowRequestDTO.java
  src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#119 :sparkles: [Feat]: 레크레이션 리뷰 전체 개수 추가
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
Labels: :sparkles: feature

#123 :ambulance: [HOTFIX!]: 플로우 스크랩, 플로우 생성 수정
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/dto/reqeust/FlowRequestDTO.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/repository/FlowRepository.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :bug: bug

#122 :sparkles: [Feat] 레크레이션 대표 이미지 추가
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
Labels: :sparkles: feature

#117 ♻️ [Refactor]: 플로우 상세조회시 커스텀 레크레이션도 조회될 수 있게 변경
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
Labels: :recycle: refactor

#125 :bug: [Fix]: DynamicUpdate, DynamicInsert 추가
  src/main/java/com/avab/avab/domain/Flow.java
Labels: :bug: bug

#127 :sparkles: [Feat]: 내 정보 조회 API 구현
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/UserConverter.java
  src/main/java/com/avab/avab/dto/response/UserResponseDTO.java
Labels: :sparkles: feature

#128 :sparkles: [Feat]: flow 수정 구현(일단 모두 삭제한 후 작성으로 구현)
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/domain/mapping/FlowRecreation.java
  src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
  src/main/java/com/avab/avab/repository/FlowAgeRepository.java
  src/main/java/com/avab/avab/repository/FlowGenderRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationKeywordRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationPurposeRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationRepository.java
  src/main/java/com/avab/avab/security/SecurityConfig.java
  src/main/java/com/avab/avab/service/FlowService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#130 ✨ [Feat]: 디스코드 알림 기능 추가 + 기타
  build.gradle
  src/main/java/com/avab/avab/AvAbApplication.java
  src/main/java/com/avab/avab/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/avab/avab/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/avab/avab/controller/FlowController.java
  src/main/java/com/avab/avab/controller/UserController.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/dto/reqeust/UserRequestDTO.java
  src/main/java/com/avab/avab/feign/discord/DiscordFeignConfiguration.java
  src/main/java/com/avab/avab/feign/discord/dto/DiscordMessage.java
  src/main/java/com/avab/avab/feign/discord/service/DiscordClient.java
  src/main/java/com/avab/avab/repository/CustomRecreationRepository.java
  src/main/java/com/avab/avab/repository/FlowAgeRepository.java
  src/main/java/com/avab/avab/repository/FlowGenderRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationKeywordRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationPurposeRepository.java
  src/main/java/com/avab/avab/repository/FlowRecreationRepository.java
  src/main/java/com/avab/avab/service/UserService.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
  src/main/java/com/avab/avab/service/impl/UserServiceImpl.java
Labels: :sparkles: feature

#132 :sparkles: [Feat]: 플로우 랜덤 이미지 추가
  src/main/generated/com/avab/avab/domain/QFlow.java
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/domain/Flow.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
  src/main/java/com/avab/avab/service/impl/FlowServiceImpl.java
Labels: :sparkles: feature

#133 :recycle: [Refactor]: 이미지 url flow 안으로 변경
  src/main/java/com/avab/avab/converter/FlowConverter.java
  src/main/java/com/avab/avab/dto/response/FlowResponseDTO.java
Labels: :recycle: refactor

#135 ✨ [Feat]: 레크레이션 추천 기능 플레이타임 추가
  src/main/java/com/avab/avab/controller/RecreationController.java
  src/main/java/com/avab/avab/converter/RecreationConverter.java
  src/main/java/com/avab/avab/dto/response/RecreationResponseDTO.java
Labels: :sparkles: feature

#137 :ambulance: [HOTFIX!]: 사용자 프로필 이미지 추가
  src/main/generated/com/avab/avab/domain/QUser.java
  src/main/java/com/avab/avab/converter/UserConverter.java
  src/main/java/com/avab/avab/domain/User.java
  src/main/java/com/avab/avab/dto/response/UserResponseDTO.java
Labels: :bug: bug
